// Autogenerated by typings-for-css-modules-loader, do not modify

export const ellipticText: string;
export const ellipticTitle: string;
export const antialiasedText: string;
export const buttonGroupWrapper: string;
export const buttonGroupItem: string;
export const buttonGroupLabel: string;
