// Autogenerated by typings-for-css-modules-loader, do not modify

export const ellipticText: string;
export const ellipticTitle: string;
export const antialiasedText: string;
export const button: string;
export const secondaryButton: string;
export const filledButton: string;
export const cancelButton: string;
export const dangerButton: string;
export const iconButton: string;
export const submitting: string;
export const disabled: string;
export const rowButton: string;
export const alignRightButton: string;
export const inputButton: string;
