// Autogenerated by typings-for-css-modules-loader, do not modify

export const ellipticText: string;
export const ellipticTitle: string;
export const antialiasedText: string;
export const checkbox: string;
export const checkboxLabel: string;
export const disabled: string;
export const customCheckbox: string;
export const checkboxLabelText: string;
export const inlineCheckbox: string;
export const wizardCheckbox: string;
