// Autogenerated by typings-for-css-modules-loader, do not modify

export const ellipticText: string;
export const ellipticTitle: string;
export const antialiasedText: string;
export const dateTimepicker: string;
export const datePickerWrapper: string;
export const datePicker: string;
export const reset: string;
export const timePicker: string;
export const timePickerDisabled: string;
export const timePickerLeftBorder: string;
export const timePickerFullWidth: string;
