// Autogenerated by typings-for-css-modules-loader, do not modify

export const ellipticText: string;
export const ellipticTitle: string;
export const antialiasedText: string;
export const radioWrapper: string;
export const radio: string;
export const radioLabel: string;
export const customRadio: string;
export const radioLabelText: string;
export const withDescription: string;
export const radioLabelDescription: string;
