// Autogenerated by typings-for-css-modules-loader, do not modify

export const ellipticText: string;
export const ellipticTitle: string;
export const antialiasedText: string;
export const undoRedo: string;
export const button: string;
export const disabled: string;
